/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.addkpi_ci;
import com.astra.anblicks.pdca.model.addkpi_ciModel;
import com.astra.anblicks.pdca.model.addkpi_ciSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the addkpi_ci service. Represents a row in the &quot;addkpi_ci&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link addkpi_ciModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link addkpi_ciImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see addkpi_ciImpl
 * @see addkpi_ci
 * @see addkpi_ciModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class addkpi_ciModelImpl extends BaseModelImpl<addkpi_ci>
	implements addkpi_ciModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a addkpi_ci model instance should use the {@link addkpi_ci} interface instead.
	 */
	public static final String TABLE_NAME = "addkpi_ci";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "addKpiId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "year", Types.BIGINT },
			{ "strategyType", Types.VARCHAR },
			{ "strategy", Types.VARCHAR },
			{ "target", Types.VARCHAR },
			{ "kpi", Types.VARCHAR },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("addKpiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("year", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("strategyType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("strategy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("target", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kpi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table addkpi_ci (uuid_ VARCHAR(75) null,addKpiId LONG not null primary key,companyId LONG,year LONG,strategyType VARCHAR(75) null,strategy VARCHAR(75) null,target VARCHAR(75) null,kpi VARCHAR(75) null,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table addkpi_ci";
	public static final String ORDER_BY_JPQL = " ORDER BY addkpi_ci.addKpiId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY addkpi_ci.addKpiId ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.astra.anblicks.pdca.model.addkpi_ci"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.astra.anblicks.pdca.model.addkpi_ci"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.astra.anblicks.pdca.model.addkpi_ci"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long UUID_COLUMN_BITMASK = 2L;
	public static final long ADDKPIID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static addkpi_ci toModel(addkpi_ciSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		addkpi_ci model = new addkpi_ciImpl();

		model.setUuid(soapModel.getUuid());
		model.setAddKpiId(soapModel.getAddKpiId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setYear(soapModel.getYear());
		model.setStrategyType(soapModel.getStrategyType());
		model.setStrategy(soapModel.getStrategy());
		model.setTarget(soapModel.getTarget());
		model.setKpi(soapModel.getKpi());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<addkpi_ci> toModels(addkpi_ciSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<addkpi_ci> models = new ArrayList<addkpi_ci>(soapModels.length);

		for (addkpi_ciSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"lock.expiration.time.com.astra.anblicks.pdca.model.addkpi_ci"));

	public addkpi_ciModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _addKpiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAddKpiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _addKpiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return addkpi_ci.class;
	}

	@Override
	public String getModelClassName() {
		return addkpi_ci.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("addKpiId", getAddKpiId());
		attributes.put("companyId", getCompanyId());
		attributes.put("year", getYear());
		attributes.put("strategyType", getStrategyType());
		attributes.put("strategy", getStrategy());
		attributes.put("target", getTarget());
		attributes.put("kpi", getKpi());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long addKpiId = (Long)attributes.get("addKpiId");

		if (addKpiId != null) {
			setAddKpiId(addKpiId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long year = (Long)attributes.get("year");

		if (year != null) {
			setYear(year);
		}

		String strategyType = (String)attributes.get("strategyType");

		if (strategyType != null) {
			setStrategyType(strategyType);
		}

		String strategy = (String)attributes.get("strategy");

		if (strategy != null) {
			setStrategy(strategy);
		}

		String target = (String)attributes.get("target");

		if (target != null) {
			setTarget(target);
		}

		String kpi = (String)attributes.get("kpi");

		if (kpi != null) {
			setKpi(kpi);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getAddKpiId() {
		return _addKpiId;
	}

	@Override
	public void setAddKpiId(long addKpiId) {
		_addKpiId = addKpiId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getYear() {
		return _year;
	}

	@Override
	public void setYear(long year) {
		_year = year;
	}

	@JSON
	@Override
	public String getStrategyType() {
		if (_strategyType == null) {
			return StringPool.BLANK;
		}
		else {
			return _strategyType;
		}
	}

	@Override
	public void setStrategyType(String strategyType) {
		_strategyType = strategyType;
	}

	@JSON
	@Override
	public String getStrategy() {
		if (_strategy == null) {
			return StringPool.BLANK;
		}
		else {
			return _strategy;
		}
	}

	@Override
	public void setStrategy(String strategy) {
		_strategy = strategy;
	}

	@JSON
	@Override
	public String getTarget() {
		if (_target == null) {
			return StringPool.BLANK;
		}
		else {
			return _target;
		}
	}

	@Override
	public void setTarget(String target) {
		_target = target;
	}

	@JSON
	@Override
	public String getKpi() {
		if (_kpi == null) {
			return StringPool.BLANK;
		}
		else {
			return _kpi;
		}
	}

	@Override
	public void setKpi(String kpi) {
		_kpi = kpi;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				addkpi_ci.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			addkpi_ci.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public addkpi_ci toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (addkpi_ci)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		addkpi_ciImpl addkpi_ciImpl = new addkpi_ciImpl();

		addkpi_ciImpl.setUuid(getUuid());
		addkpi_ciImpl.setAddKpiId(getAddKpiId());
		addkpi_ciImpl.setCompanyId(getCompanyId());
		addkpi_ciImpl.setYear(getYear());
		addkpi_ciImpl.setStrategyType(getStrategyType());
		addkpi_ciImpl.setStrategy(getStrategy());
		addkpi_ciImpl.setTarget(getTarget());
		addkpi_ciImpl.setKpi(getKpi());
		addkpi_ciImpl.setUserId(getUserId());
		addkpi_ciImpl.setUserName(getUserName());
		addkpi_ciImpl.setCreateDate(getCreateDate());
		addkpi_ciImpl.setModifiedDate(getModifiedDate());

		addkpi_ciImpl.resetOriginalValues();

		return addkpi_ciImpl;
	}

	@Override
	public int compareTo(addkpi_ci addkpi_ci) {
		long primaryKey = addkpi_ci.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof addkpi_ci)) {
			return false;
		}

		addkpi_ci addkpi_ci = (addkpi_ci)obj;

		long primaryKey = addkpi_ci.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		addkpi_ciModelImpl addkpi_ciModelImpl = this;

		addkpi_ciModelImpl._originalUuid = addkpi_ciModelImpl._uuid;

		addkpi_ciModelImpl._originalCompanyId = addkpi_ciModelImpl._companyId;

		addkpi_ciModelImpl._setOriginalCompanyId = false;

		addkpi_ciModelImpl._setModifiedDate = false;

		addkpi_ciModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<addkpi_ci> toCacheModel() {
		addkpi_ciCacheModel addkpi_ciCacheModel = new addkpi_ciCacheModel();

		addkpi_ciCacheModel.uuid = getUuid();

		String uuid = addkpi_ciCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			addkpi_ciCacheModel.uuid = null;
		}

		addkpi_ciCacheModel.addKpiId = getAddKpiId();

		addkpi_ciCacheModel.companyId = getCompanyId();

		addkpi_ciCacheModel.year = getYear();

		addkpi_ciCacheModel.strategyType = getStrategyType();

		String strategyType = addkpi_ciCacheModel.strategyType;

		if ((strategyType != null) && (strategyType.length() == 0)) {
			addkpi_ciCacheModel.strategyType = null;
		}

		addkpi_ciCacheModel.strategy = getStrategy();

		String strategy = addkpi_ciCacheModel.strategy;

		if ((strategy != null) && (strategy.length() == 0)) {
			addkpi_ciCacheModel.strategy = null;
		}

		addkpi_ciCacheModel.target = getTarget();

		String target = addkpi_ciCacheModel.target;

		if ((target != null) && (target.length() == 0)) {
			addkpi_ciCacheModel.target = null;
		}

		addkpi_ciCacheModel.kpi = getKpi();

		String kpi = addkpi_ciCacheModel.kpi;

		if ((kpi != null) && (kpi.length() == 0)) {
			addkpi_ciCacheModel.kpi = null;
		}

		addkpi_ciCacheModel.userId = getUserId();

		addkpi_ciCacheModel.userName = getUserName();

		String userName = addkpi_ciCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			addkpi_ciCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			addkpi_ciCacheModel.createDate = createDate.getTime();
		}
		else {
			addkpi_ciCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			addkpi_ciCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			addkpi_ciCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return addkpi_ciCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", addKpiId=");
		sb.append(getAddKpiId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", year=");
		sb.append(getYear());
		sb.append(", strategyType=");
		sb.append(getStrategyType());
		sb.append(", strategy=");
		sb.append(getStrategy());
		sb.append(", target=");
		sb.append(getTarget());
		sb.append(", kpi=");
		sb.append(getKpi());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.astra.anblicks.pdca.model.addkpi_ci");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>addKpiId</column-name><column-value><![CDATA[");
		sb.append(getAddKpiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>strategyType</column-name><column-value><![CDATA[");
		sb.append(getStrategyType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>strategy</column-name><column-value><![CDATA[");
		sb.append(getStrategy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>target</column-name><column-value><![CDATA[");
		sb.append(getTarget());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kpi</column-name><column-value><![CDATA[");
		sb.append(getKpi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = addkpi_ci.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			addkpi_ci.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _addKpiId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _year;
	private String _strategyType;
	private String _strategy;
	private String _target;
	private String _kpi;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private addkpi_ci _escapedModel;
}