/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.addkpi_ci;
import com.astra.anblicks.pdca.service.addkpi_ciLocalServiceUtil;

/**
 * The extended model base implementation for the addkpi_ci service. Represents a row in the &quot;addkpi_ci&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link addkpi_ciImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see addkpi_ciImpl
 * @see addkpi_ci
 * @generated
 */
@ProviderType
public abstract class addkpi_ciBaseImpl extends addkpi_ciModelImpl
	implements addkpi_ci {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a addkpi_ci model instance should use the {@link addkpi_ci} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			addkpi_ciLocalServiceUtil.addaddkpi_ci(this);
		}
		else {
			addkpi_ciLocalServiceUtil.updateaddkpi_ci(this);
		}
	}
}