/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.ci_kpi;
import com.astra.anblicks.pdca.service.ci_kpiLocalServiceUtil;

/**
 * The extended model base implementation for the ci_kpi service. Represents a row in the &quot;ci_kpi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ci_kpiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ci_kpiImpl
 * @see ci_kpi
 * @generated
 */
@ProviderType
public abstract class ci_kpiBaseImpl extends ci_kpiModelImpl implements ci_kpi {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ci_kpi model instance should use the {@link ci_kpi} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ci_kpiLocalServiceUtil.addci_kpi(this);
		}
		else {
			ci_kpiLocalServiceUtil.updateci_kpi(this);
		}
	}
}