/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.ci_kpi;
import com.astra.anblicks.pdca.model.ci_kpiModel;
import com.astra.anblicks.pdca.model.ci_kpiSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ci_kpi service. Represents a row in the &quot;ci_kpi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ci_kpiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ci_kpiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ci_kpiImpl
 * @see ci_kpi
 * @see ci_kpiModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ci_kpiModelImpl extends BaseModelImpl<ci_kpi>
	implements ci_kpiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ci_kpi model instance should use the {@link ci_kpi} interface instead.
	 */
	public static final String TABLE_NAME = "ci_kpi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "ciKpiId", Types.BIGINT },
			{ "addKpiId", Types.BIGINT },
			{ "ciPeriodId", Types.BIGINT },
			{ "targetYTD", Types.VARCHAR },
			{ "problemIdentification", Types.VARCHAR },
			{ "proposedAction", Types.VARCHAR },
			{ "achivement", Types.VARCHAR },
			{ "status", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ciKpiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("addKpiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ciPeriodId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("targetYTD", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("problemIdentification", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("proposedAction", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("achivement", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table ci_kpi (uuid_ VARCHAR(75) null,ciKpiId LONG not null primary key,addKpiId LONG,ciPeriodId LONG,targetYTD VARCHAR(75) null,problemIdentification VARCHAR(75) null,proposedAction VARCHAR(75) null,achivement VARCHAR(75) null,status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ci_kpi";
	public static final String ORDER_BY_JPQL = " ORDER BY ci_kpi.ciKpiId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ci_kpi.ciKpiId ASC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.astra.anblicks.pdca.model.ci_kpi"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.astra.anblicks.pdca.model.ci_kpi"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.astra.anblicks.pdca.model.ci_kpi"),
			true);
	public static final long UUID_COLUMN_BITMASK = 1L;
	public static final long CIKPIID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ci_kpi toModel(ci_kpiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ci_kpi model = new ci_kpiImpl();

		model.setUuid(soapModel.getUuid());
		model.setCiKpiId(soapModel.getCiKpiId());
		model.setAddKpiId(soapModel.getAddKpiId());
		model.setCiPeriodId(soapModel.getCiPeriodId());
		model.setTargetYTD(soapModel.getTargetYTD());
		model.setProblemIdentification(soapModel.getProblemIdentification());
		model.setProposedAction(soapModel.getProposedAction());
		model.setAchivement(soapModel.getAchivement());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ci_kpi> toModels(ci_kpiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ci_kpi> models = new ArrayList<ci_kpi>(soapModels.length);

		for (ci_kpiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"lock.expiration.time.com.astra.anblicks.pdca.model.ci_kpi"));

	public ci_kpiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ciKpiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCiKpiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ciKpiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ci_kpi.class;
	}

	@Override
	public String getModelClassName() {
		return ci_kpi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("ciKpiId", getCiKpiId());
		attributes.put("addKpiId", getAddKpiId());
		attributes.put("ciPeriodId", getCiPeriodId());
		attributes.put("targetYTD", getTargetYTD());
		attributes.put("problemIdentification", getProblemIdentification());
		attributes.put("proposedAction", getProposedAction());
		attributes.put("achivement", getAchivement());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long ciKpiId = (Long)attributes.get("ciKpiId");

		if (ciKpiId != null) {
			setCiKpiId(ciKpiId);
		}

		Long addKpiId = (Long)attributes.get("addKpiId");

		if (addKpiId != null) {
			setAddKpiId(addKpiId);
		}

		Long ciPeriodId = (Long)attributes.get("ciPeriodId");

		if (ciPeriodId != null) {
			setCiPeriodId(ciPeriodId);
		}

		String targetYTD = (String)attributes.get("targetYTD");

		if (targetYTD != null) {
			setTargetYTD(targetYTD);
		}

		String problemIdentification = (String)attributes.get(
				"problemIdentification");

		if (problemIdentification != null) {
			setProblemIdentification(problemIdentification);
		}

		String proposedAction = (String)attributes.get("proposedAction");

		if (proposedAction != null) {
			setProposedAction(proposedAction);
		}

		String achivement = (String)attributes.get("achivement");

		if (achivement != null) {
			setAchivement(achivement);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCiKpiId() {
		return _ciKpiId;
	}

	@Override
	public void setCiKpiId(long ciKpiId) {
		_ciKpiId = ciKpiId;
	}

	@JSON
	@Override
	public long getAddKpiId() {
		return _addKpiId;
	}

	@Override
	public void setAddKpiId(long addKpiId) {
		_addKpiId = addKpiId;
	}

	@JSON
	@Override
	public long getCiPeriodId() {
		return _ciPeriodId;
	}

	@Override
	public void setCiPeriodId(long ciPeriodId) {
		_ciPeriodId = ciPeriodId;
	}

	@JSON
	@Override
	public String getTargetYTD() {
		if (_targetYTD == null) {
			return StringPool.BLANK;
		}
		else {
			return _targetYTD;
		}
	}

	@Override
	public void setTargetYTD(String targetYTD) {
		_targetYTD = targetYTD;
	}

	@JSON
	@Override
	public String getProblemIdentification() {
		if (_problemIdentification == null) {
			return StringPool.BLANK;
		}
		else {
			return _problemIdentification;
		}
	}

	@Override
	public void setProblemIdentification(String problemIdentification) {
		_problemIdentification = problemIdentification;
	}

	@JSON
	@Override
	public String getProposedAction() {
		if (_proposedAction == null) {
			return StringPool.BLANK;
		}
		else {
			return _proposedAction;
		}
	}

	@Override
	public void setProposedAction(String proposedAction) {
		_proposedAction = proposedAction;
	}

	@JSON
	@Override
	public String getAchivement() {
		if (_achivement == null) {
			return StringPool.BLANK;
		}
		else {
			return _achivement;
		}
	}

	@Override
	public void setAchivement(String achivement) {
		_achivement = achivement;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ci_kpi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ci_kpi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ci_kpi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ci_kpiImpl ci_kpiImpl = new ci_kpiImpl();

		ci_kpiImpl.setUuid(getUuid());
		ci_kpiImpl.setCiKpiId(getCiKpiId());
		ci_kpiImpl.setAddKpiId(getAddKpiId());
		ci_kpiImpl.setCiPeriodId(getCiPeriodId());
		ci_kpiImpl.setTargetYTD(getTargetYTD());
		ci_kpiImpl.setProblemIdentification(getProblemIdentification());
		ci_kpiImpl.setProposedAction(getProposedAction());
		ci_kpiImpl.setAchivement(getAchivement());
		ci_kpiImpl.setStatus(getStatus());

		ci_kpiImpl.resetOriginalValues();

		return ci_kpiImpl;
	}

	@Override
	public int compareTo(ci_kpi ci_kpi) {
		long primaryKey = ci_kpi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ci_kpi)) {
			return false;
		}

		ci_kpi ci_kpi = (ci_kpi)obj;

		long primaryKey = ci_kpi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ci_kpiModelImpl ci_kpiModelImpl = this;

		ci_kpiModelImpl._originalUuid = ci_kpiModelImpl._uuid;

		ci_kpiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ci_kpi> toCacheModel() {
		ci_kpiCacheModel ci_kpiCacheModel = new ci_kpiCacheModel();

		ci_kpiCacheModel.uuid = getUuid();

		String uuid = ci_kpiCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ci_kpiCacheModel.uuid = null;
		}

		ci_kpiCacheModel.ciKpiId = getCiKpiId();

		ci_kpiCacheModel.addKpiId = getAddKpiId();

		ci_kpiCacheModel.ciPeriodId = getCiPeriodId();

		ci_kpiCacheModel.targetYTD = getTargetYTD();

		String targetYTD = ci_kpiCacheModel.targetYTD;

		if ((targetYTD != null) && (targetYTD.length() == 0)) {
			ci_kpiCacheModel.targetYTD = null;
		}

		ci_kpiCacheModel.problemIdentification = getProblemIdentification();

		String problemIdentification = ci_kpiCacheModel.problemIdentification;

		if ((problemIdentification != null) &&
				(problemIdentification.length() == 0)) {
			ci_kpiCacheModel.problemIdentification = null;
		}

		ci_kpiCacheModel.proposedAction = getProposedAction();

		String proposedAction = ci_kpiCacheModel.proposedAction;

		if ((proposedAction != null) && (proposedAction.length() == 0)) {
			ci_kpiCacheModel.proposedAction = null;
		}

		ci_kpiCacheModel.achivement = getAchivement();

		String achivement = ci_kpiCacheModel.achivement;

		if ((achivement != null) && (achivement.length() == 0)) {
			ci_kpiCacheModel.achivement = null;
		}

		ci_kpiCacheModel.status = getStatus();

		String status = ci_kpiCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			ci_kpiCacheModel.status = null;
		}

		return ci_kpiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", ciKpiId=");
		sb.append(getCiKpiId());
		sb.append(", addKpiId=");
		sb.append(getAddKpiId());
		sb.append(", ciPeriodId=");
		sb.append(getCiPeriodId());
		sb.append(", targetYTD=");
		sb.append(getTargetYTD());
		sb.append(", problemIdentification=");
		sb.append(getProblemIdentification());
		sb.append(", proposedAction=");
		sb.append(getProposedAction());
		sb.append(", achivement=");
		sb.append(getAchivement());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.astra.anblicks.pdca.model.ci_kpi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ciKpiId</column-name><column-value><![CDATA[");
		sb.append(getCiKpiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>addKpiId</column-name><column-value><![CDATA[");
		sb.append(getAddKpiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ciPeriodId</column-name><column-value><![CDATA[");
		sb.append(getCiPeriodId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>targetYTD</column-name><column-value><![CDATA[");
		sb.append(getTargetYTD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>problemIdentification</column-name><column-value><![CDATA[");
		sb.append(getProblemIdentification());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>proposedAction</column-name><column-value><![CDATA[");
		sb.append(getProposedAction());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>achivement</column-name><column-value><![CDATA[");
		sb.append(getAchivement());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ci_kpi.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ci_kpi.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _ciKpiId;
	private long _addKpiId;
	private long _ciPeriodId;
	private String _targetYTD;
	private String _problemIdentification;
	private String _proposedAction;
	private String _achivement;
	private String _status;
	private long _columnBitmask;
	private ci_kpi _escapedModel;
}