/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the addkpi_ci service. Represents a row in the &quot;addkpi_ci&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.addkpi_ciModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.addkpi_ciImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see addkpi_ci
 * @see com.astra.anblicks.pdca.model.impl.addkpi_ciImpl
 * @see com.astra.anblicks.pdca.model.impl.addkpi_ciModelImpl
 * @generated
 */
@ProviderType
public interface addkpi_ciModel extends BaseModel<addkpi_ci>, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a addkpi_ci model instance should use the {@link addkpi_ci} interface instead.
	 */

	/**
	 * Returns the primary key of this addkpi_ci.
	 *
	 * @return the primary key of this addkpi_ci
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this addkpi_ci.
	 *
	 * @param primaryKey the primary key of this addkpi_ci
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this addkpi_ci.
	 *
	 * @return the uuid of this addkpi_ci
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this addkpi_ci.
	 *
	 * @param uuid the uuid of this addkpi_ci
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the add kpi ID of this addkpi_ci.
	 *
	 * @return the add kpi ID of this addkpi_ci
	 */
	public long getAddKpiId();

	/**
	 * Sets the add kpi ID of this addkpi_ci.
	 *
	 * @param addKpiId the add kpi ID of this addkpi_ci
	 */
	public void setAddKpiId(long addKpiId);

	/**
	 * Returns the company ID of this addkpi_ci.
	 *
	 * @return the company ID of this addkpi_ci
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this addkpi_ci.
	 *
	 * @param companyId the company ID of this addkpi_ci
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the year of this addkpi_ci.
	 *
	 * @return the year of this addkpi_ci
	 */
	public long getYear();

	/**
	 * Sets the year of this addkpi_ci.
	 *
	 * @param year the year of this addkpi_ci
	 */
	public void setYear(long year);

	/**
	 * Returns the strategy type of this addkpi_ci.
	 *
	 * @return the strategy type of this addkpi_ci
	 */
	@AutoEscape
	public String getStrategyType();

	/**
	 * Sets the strategy type of this addkpi_ci.
	 *
	 * @param strategyType the strategy type of this addkpi_ci
	 */
	public void setStrategyType(String strategyType);

	/**
	 * Returns the strategy of this addkpi_ci.
	 *
	 * @return the strategy of this addkpi_ci
	 */
	@AutoEscape
	public String getStrategy();

	/**
	 * Sets the strategy of this addkpi_ci.
	 *
	 * @param strategy the strategy of this addkpi_ci
	 */
	public void setStrategy(String strategy);

	/**
	 * Returns the target of this addkpi_ci.
	 *
	 * @return the target of this addkpi_ci
	 */
	@AutoEscape
	public String getTarget();

	/**
	 * Sets the target of this addkpi_ci.
	 *
	 * @param target the target of this addkpi_ci
	 */
	public void setTarget(String target);

	/**
	 * Returns the kpi of this addkpi_ci.
	 *
	 * @return the kpi of this addkpi_ci
	 */
	@AutoEscape
	public String getKpi();

	/**
	 * Sets the kpi of this addkpi_ci.
	 *
	 * @param kpi the kpi of this addkpi_ci
	 */
	public void setKpi(String kpi);

	/**
	 * Returns the user ID of this addkpi_ci.
	 *
	 * @return the user ID of this addkpi_ci
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this addkpi_ci.
	 *
	 * @param userId the user ID of this addkpi_ci
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this addkpi_ci.
	 *
	 * @return the user uuid of this addkpi_ci
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this addkpi_ci.
	 *
	 * @param userUuid the user uuid of this addkpi_ci
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this addkpi_ci.
	 *
	 * @return the user name of this addkpi_ci
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this addkpi_ci.
	 *
	 * @param userName the user name of this addkpi_ci
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this addkpi_ci.
	 *
	 * @return the create date of this addkpi_ci
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this addkpi_ci.
	 *
	 * @param createDate the create date of this addkpi_ci
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this addkpi_ci.
	 *
	 * @return the modified date of this addkpi_ci
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this addkpi_ci.
	 *
	 * @param modifiedDate the modified date of this addkpi_ci
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.astra.anblicks.pdca.model.addkpi_ci addkpi_ci);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.astra.anblicks.pdca.model.addkpi_ci> toCacheModel();

	@Override
	public com.astra.anblicks.pdca.model.addkpi_ci toEscapedModel();

	@Override
	public com.astra.anblicks.pdca.model.addkpi_ci toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}