/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ci_kpi service. Represents a row in the &quot;ci_kpi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.ci_kpiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.ci_kpiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ci_kpi
 * @see com.astra.anblicks.pdca.model.impl.ci_kpiImpl
 * @see com.astra.anblicks.pdca.model.impl.ci_kpiModelImpl
 * @generated
 */
@ProviderType
public interface ci_kpiModel extends BaseModel<ci_kpi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ci_kpi model instance should use the {@link ci_kpi} interface instead.
	 */

	/**
	 * Returns the primary key of this ci_kpi.
	 *
	 * @return the primary key of this ci_kpi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ci_kpi.
	 *
	 * @param primaryKey the primary key of this ci_kpi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ci_kpi.
	 *
	 * @return the uuid of this ci_kpi
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this ci_kpi.
	 *
	 * @param uuid the uuid of this ci_kpi
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ci kpi ID of this ci_kpi.
	 *
	 * @return the ci kpi ID of this ci_kpi
	 */
	public long getCiKpiId();

	/**
	 * Sets the ci kpi ID of this ci_kpi.
	 *
	 * @param ciKpiId the ci kpi ID of this ci_kpi
	 */
	public void setCiKpiId(long ciKpiId);

	/**
	 * Returns the add kpi ID of this ci_kpi.
	 *
	 * @return the add kpi ID of this ci_kpi
	 */
	public long getAddKpiId();

	/**
	 * Sets the add kpi ID of this ci_kpi.
	 *
	 * @param addKpiId the add kpi ID of this ci_kpi
	 */
	public void setAddKpiId(long addKpiId);

	/**
	 * Returns the ci period ID of this ci_kpi.
	 *
	 * @return the ci period ID of this ci_kpi
	 */
	public long getCiPeriodId();

	/**
	 * Sets the ci period ID of this ci_kpi.
	 *
	 * @param ciPeriodId the ci period ID of this ci_kpi
	 */
	public void setCiPeriodId(long ciPeriodId);

	/**
	 * Returns the target ytd of this ci_kpi.
	 *
	 * @return the target ytd of this ci_kpi
	 */
	@AutoEscape
	public String getTargetYTD();

	/**
	 * Sets the target ytd of this ci_kpi.
	 *
	 * @param targetYTD the target ytd of this ci_kpi
	 */
	public void setTargetYTD(String targetYTD);

	/**
	 * Returns the problem identification of this ci_kpi.
	 *
	 * @return the problem identification of this ci_kpi
	 */
	@AutoEscape
	public String getProblemIdentification();

	/**
	 * Sets the problem identification of this ci_kpi.
	 *
	 * @param problemIdentification the problem identification of this ci_kpi
	 */
	public void setProblemIdentification(String problemIdentification);

	/**
	 * Returns the proposed action of this ci_kpi.
	 *
	 * @return the proposed action of this ci_kpi
	 */
	@AutoEscape
	public String getProposedAction();

	/**
	 * Sets the proposed action of this ci_kpi.
	 *
	 * @param proposedAction the proposed action of this ci_kpi
	 */
	public void setProposedAction(String proposedAction);

	/**
	 * Returns the achivement of this ci_kpi.
	 *
	 * @return the achivement of this ci_kpi
	 */
	@AutoEscape
	public String getAchivement();

	/**
	 * Sets the achivement of this ci_kpi.
	 *
	 * @param achivement the achivement of this ci_kpi
	 */
	public void setAchivement(String achivement);

	/**
	 * Returns the status of this ci_kpi.
	 *
	 * @return the status of this ci_kpi
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this ci_kpi.
	 *
	 * @param status the status of this ci_kpi
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.astra.anblicks.pdca.model.ci_kpi ci_kpi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.astra.anblicks.pdca.model.ci_kpi> toCacheModel();

	@Override
	public com.astra.anblicks.pdca.model.ci_kpi toEscapedModel();

	@Override
	public com.astra.anblicks.pdca.model.ci_kpi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}