/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.service.base;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.addkpi_ci;
import com.astra.anblicks.pdca.service.addkpi_ciLocalService;
import com.astra.anblicks.pdca.service.persistence.AstraPdca_CompanyDataPersistence;
import com.astra.anblicks.pdca.service.persistence.AstraPdca_ModulePersistence;
import com.astra.anblicks.pdca.service.persistence.AstraPdca_YearPersistence;
import com.astra.anblicks.pdca.service.persistence.achivementFormulaPersistence;
import com.astra.anblicks.pdca.service.persistence.addkpi_ciPersistence;
import com.astra.anblicks.pdca.service.persistence.ci_kpiPersistence;
import com.astra.anblicks.pdca.service.persistence.cla_kpiPersistence;
import com.astra.anblicks.pdca.service.persistence.companyPersistence;
import com.astra.anblicks.pdca.service.persistence.company_userPersistence;
import com.astra.anblicks.pdca.service.persistence.itemDescriptionPersistence;
import com.astra.anblicks.pdca.service.persistence.kpiPersistence;
import com.astra.anblicks.pdca.service.persistence.pdca_AdminSettingsPersistence;
import com.astra.anblicks.pdca.service.persistence.periodPersistence;
import com.astra.anblicks.pdca.service.persistence.tradingProfitPersistence;
import com.astra.anblicks.pdca.service.persistence.typePersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the addkpi_ci local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.astra.anblicks.pdca.service.impl.addkpi_ciLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.astra.anblicks.pdca.service.impl.addkpi_ciLocalServiceImpl
 * @see com.astra.anblicks.pdca.service.addkpi_ciLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class addkpi_ciLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements addkpi_ciLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.astra.anblicks.pdca.service.addkpi_ciLocalServiceUtil} to access the addkpi_ci local service.
	 */

	/**
	 * Adds the addkpi_ci to the database. Also notifies the appropriate model listeners.
	 *
	 * @param addkpi_ci the addkpi_ci
	 * @return the addkpi_ci that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public addkpi_ci addaddkpi_ci(addkpi_ci addkpi_ci) {
		addkpi_ci.setNew(true);

		return addkpi_ciPersistence.update(addkpi_ci);
	}

	/**
	 * Creates a new addkpi_ci with the primary key. Does not add the addkpi_ci to the database.
	 *
	 * @param addKpiId the primary key for the new addkpi_ci
	 * @return the new addkpi_ci
	 */
	@Override
	public addkpi_ci createaddkpi_ci(long addKpiId) {
		return addkpi_ciPersistence.create(addKpiId);
	}

	/**
	 * Deletes the addkpi_ci with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param addKpiId the primary key of the addkpi_ci
	 * @return the addkpi_ci that was removed
	 * @throws PortalException if a addkpi_ci with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public addkpi_ci deleteaddkpi_ci(long addKpiId) throws PortalException {
		return addkpi_ciPersistence.remove(addKpiId);
	}

	/**
	 * Deletes the addkpi_ci from the database. Also notifies the appropriate model listeners.
	 *
	 * @param addkpi_ci the addkpi_ci
	 * @return the addkpi_ci that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public addkpi_ci deleteaddkpi_ci(addkpi_ci addkpi_ci) {
		return addkpi_ciPersistence.remove(addkpi_ci);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(addkpi_ci.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return addkpi_ciPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.astra.anblicks.pdca.model.impl.addkpi_ciModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return addkpi_ciPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.astra.anblicks.pdca.model.impl.addkpi_ciModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return addkpi_ciPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return addkpi_ciPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return addkpi_ciPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public addkpi_ci fetchaddkpi_ci(long addKpiId) {
		return addkpi_ciPersistence.fetchByPrimaryKey(addKpiId);
	}

	/**
	 * Returns the addkpi_ci with the matching UUID and company.
	 *
	 * @param uuid the addkpi_ci's UUID
	 * @param companyId the primary key of the company
	 * @return the matching addkpi_ci, or <code>null</code> if a matching addkpi_ci could not be found
	 */
	@Override
	public addkpi_ci fetchaddkpi_ciByUuidAndCompanyId(String uuid,
		long companyId) {
		return addkpi_ciPersistence.fetchByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns the addkpi_ci with the primary key.
	 *
	 * @param addKpiId the primary key of the addkpi_ci
	 * @return the addkpi_ci
	 * @throws PortalException if a addkpi_ci with the primary key could not be found
	 */
	@Override
	public addkpi_ci getaddkpi_ci(long addKpiId) throws PortalException {
		return addkpi_ciPersistence.findByPrimaryKey(addKpiId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(addkpi_ciLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(addkpi_ci.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("addKpiId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(addkpi_ciLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(addkpi_ci.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("addKpiId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(addkpi_ciLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(addkpi_ci.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("addKpiId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {
		final ExportActionableDynamicQuery exportActionableDynamicQuery = new ExportActionableDynamicQuery() {
				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary = portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(stagedModelType,
						modelAdditionCount);

					long modelDeletionCount = ExportImportHelperUtil.getModelDeletionCount(portletDataContext,
							stagedModelType);

					manifestSummary.addModelDeletionCount(stagedModelType,
						modelDeletionCount);

					return modelAdditionCount;
				}
			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(new ActionableDynamicQuery.AddCriteriaMethod() {
				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(dynamicQuery,
						"modifiedDate");
				}
			});

		exportActionableDynamicQuery.setCompanyId(portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(new ActionableDynamicQuery.PerformActionMethod<addkpi_ci>() {
				@Override
				public void performAction(addkpi_ci addkpi_ci)
					throws PortalException {
					StagedModelDataHandlerUtil.exportStagedModel(portletDataContext,
						addkpi_ci);
				}
			});
		exportActionableDynamicQuery.setStagedModelType(new StagedModelType(
				PortalUtil.getClassNameId(addkpi_ci.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return addkpi_ciLocalService.deleteaddkpi_ci((addkpi_ci)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return addkpi_ciPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the addkpi_ci with the matching UUID and company.
	 *
	 * @param uuid the addkpi_ci's UUID
	 * @param companyId the primary key of the company
	 * @return the matching addkpi_ci
	 * @throws PortalException if a matching addkpi_ci could not be found
	 */
	@Override
	public addkpi_ci getaddkpi_ciByUuidAndCompanyId(String uuid, long companyId)
		throws PortalException {
		return addkpi_ciPersistence.findByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns a range of all the addkpi_cis.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.astra.anblicks.pdca.model.impl.addkpi_ciModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of addkpi_cis
	 * @param end the upper bound of the range of addkpi_cis (not inclusive)
	 * @return the range of addkpi_cis
	 */
	@Override
	public List<addkpi_ci> getaddkpi_cis(int start, int end) {
		return addkpi_ciPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of addkpi_cis.
	 *
	 * @return the number of addkpi_cis
	 */
	@Override
	public int getaddkpi_cisCount() {
		return addkpi_ciPersistence.countAll();
	}

	/**
	 * Updates the addkpi_ci in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param addkpi_ci the addkpi_ci
	 * @return the addkpi_ci that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public addkpi_ci updateaddkpi_ci(addkpi_ci addkpi_ci) {
		return addkpi_ciPersistence.update(addkpi_ci);
	}

	/**
	 * Returns the achivement formula local service.
	 *
	 * @return the achivement formula local service
	 */
	public com.astra.anblicks.pdca.service.achivementFormulaLocalService getachivementFormulaLocalService() {
		return achivementFormulaLocalService;
	}

	/**
	 * Sets the achivement formula local service.
	 *
	 * @param achivementFormulaLocalService the achivement formula local service
	 */
	public void setachivementFormulaLocalService(
		com.astra.anblicks.pdca.service.achivementFormulaLocalService achivementFormulaLocalService) {
		this.achivementFormulaLocalService = achivementFormulaLocalService;
	}

	/**
	 * Returns the achivement formula persistence.
	 *
	 * @return the achivement formula persistence
	 */
	public achivementFormulaPersistence getachivementFormulaPersistence() {
		return achivementFormulaPersistence;
	}

	/**
	 * Sets the achivement formula persistence.
	 *
	 * @param achivementFormulaPersistence the achivement formula persistence
	 */
	public void setachivementFormulaPersistence(
		achivementFormulaPersistence achivementFormulaPersistence) {
		this.achivementFormulaPersistence = achivementFormulaPersistence;
	}

	/**
	 * Returns the addkpi_ci local service.
	 *
	 * @return the addkpi_ci local service
	 */
	public addkpi_ciLocalService getaddkpi_ciLocalService() {
		return addkpi_ciLocalService;
	}

	/**
	 * Sets the addkpi_ci local service.
	 *
	 * @param addkpi_ciLocalService the addkpi_ci local service
	 */
	public void setaddkpi_ciLocalService(
		addkpi_ciLocalService addkpi_ciLocalService) {
		this.addkpi_ciLocalService = addkpi_ciLocalService;
	}

	/**
	 * Returns the addkpi_ci persistence.
	 *
	 * @return the addkpi_ci persistence
	 */
	public addkpi_ciPersistence getaddkpi_ciPersistence() {
		return addkpi_ciPersistence;
	}

	/**
	 * Sets the addkpi_ci persistence.
	 *
	 * @param addkpi_ciPersistence the addkpi_ci persistence
	 */
	public void setaddkpi_ciPersistence(
		addkpi_ciPersistence addkpi_ciPersistence) {
		this.addkpi_ciPersistence = addkpi_ciPersistence;
	}

	/**
	 * Returns the astra pdca_ company data local service.
	 *
	 * @return the astra pdca_ company data local service
	 */
	public com.astra.anblicks.pdca.service.AstraPdca_CompanyDataLocalService getAstraPdca_CompanyDataLocalService() {
		return astraPdca_CompanyDataLocalService;
	}

	/**
	 * Sets the astra pdca_ company data local service.
	 *
	 * @param astraPdca_CompanyDataLocalService the astra pdca_ company data local service
	 */
	public void setAstraPdca_CompanyDataLocalService(
		com.astra.anblicks.pdca.service.AstraPdca_CompanyDataLocalService astraPdca_CompanyDataLocalService) {
		this.astraPdca_CompanyDataLocalService = astraPdca_CompanyDataLocalService;
	}

	/**
	 * Returns the astra pdca_ company data persistence.
	 *
	 * @return the astra pdca_ company data persistence
	 */
	public AstraPdca_CompanyDataPersistence getAstraPdca_CompanyDataPersistence() {
		return astraPdca_CompanyDataPersistence;
	}

	/**
	 * Sets the astra pdca_ company data persistence.
	 *
	 * @param astraPdca_CompanyDataPersistence the astra pdca_ company data persistence
	 */
	public void setAstraPdca_CompanyDataPersistence(
		AstraPdca_CompanyDataPersistence astraPdca_CompanyDataPersistence) {
		this.astraPdca_CompanyDataPersistence = astraPdca_CompanyDataPersistence;
	}

	/**
	 * Returns the astra pdca_ module local service.
	 *
	 * @return the astra pdca_ module local service
	 */
	public com.astra.anblicks.pdca.service.AstraPdca_ModuleLocalService getAstraPdca_ModuleLocalService() {
		return astraPdca_ModuleLocalService;
	}

	/**
	 * Sets the astra pdca_ module local service.
	 *
	 * @param astraPdca_ModuleLocalService the astra pdca_ module local service
	 */
	public void setAstraPdca_ModuleLocalService(
		com.astra.anblicks.pdca.service.AstraPdca_ModuleLocalService astraPdca_ModuleLocalService) {
		this.astraPdca_ModuleLocalService = astraPdca_ModuleLocalService;
	}

	/**
	 * Returns the astra pdca_ module persistence.
	 *
	 * @return the astra pdca_ module persistence
	 */
	public AstraPdca_ModulePersistence getAstraPdca_ModulePersistence() {
		return astraPdca_ModulePersistence;
	}

	/**
	 * Sets the astra pdca_ module persistence.
	 *
	 * @param astraPdca_ModulePersistence the astra pdca_ module persistence
	 */
	public void setAstraPdca_ModulePersistence(
		AstraPdca_ModulePersistence astraPdca_ModulePersistence) {
		this.astraPdca_ModulePersistence = astraPdca_ModulePersistence;
	}

	/**
	 * Returns the astra pdca_ year local service.
	 *
	 * @return the astra pdca_ year local service
	 */
	public com.astra.anblicks.pdca.service.AstraPdca_YearLocalService getAstraPdca_YearLocalService() {
		return astraPdca_YearLocalService;
	}

	/**
	 * Sets the astra pdca_ year local service.
	 *
	 * @param astraPdca_YearLocalService the astra pdca_ year local service
	 */
	public void setAstraPdca_YearLocalService(
		com.astra.anblicks.pdca.service.AstraPdca_YearLocalService astraPdca_YearLocalService) {
		this.astraPdca_YearLocalService = astraPdca_YearLocalService;
	}

	/**
	 * Returns the astra pdca_ year persistence.
	 *
	 * @return the astra pdca_ year persistence
	 */
	public AstraPdca_YearPersistence getAstraPdca_YearPersistence() {
		return astraPdca_YearPersistence;
	}

	/**
	 * Sets the astra pdca_ year persistence.
	 *
	 * @param astraPdca_YearPersistence the astra pdca_ year persistence
	 */
	public void setAstraPdca_YearPersistence(
		AstraPdca_YearPersistence astraPdca_YearPersistence) {
		this.astraPdca_YearPersistence = astraPdca_YearPersistence;
	}

	/**
	 * Returns the ci_kpi local service.
	 *
	 * @return the ci_kpi local service
	 */
	public com.astra.anblicks.pdca.service.ci_kpiLocalService getci_kpiLocalService() {
		return ci_kpiLocalService;
	}

	/**
	 * Sets the ci_kpi local service.
	 *
	 * @param ci_kpiLocalService the ci_kpi local service
	 */
	public void setci_kpiLocalService(
		com.astra.anblicks.pdca.service.ci_kpiLocalService ci_kpiLocalService) {
		this.ci_kpiLocalService = ci_kpiLocalService;
	}

	/**
	 * Returns the ci_kpi persistence.
	 *
	 * @return the ci_kpi persistence
	 */
	public ci_kpiPersistence getci_kpiPersistence() {
		return ci_kpiPersistence;
	}

	/**
	 * Sets the ci_kpi persistence.
	 *
	 * @param ci_kpiPersistence the ci_kpi persistence
	 */
	public void setci_kpiPersistence(ci_kpiPersistence ci_kpiPersistence) {
		this.ci_kpiPersistence = ci_kpiPersistence;
	}

	/**
	 * Returns the cla_kpi local service.
	 *
	 * @return the cla_kpi local service
	 */
	public com.astra.anblicks.pdca.service.cla_kpiLocalService getcla_kpiLocalService() {
		return cla_kpiLocalService;
	}

	/**
	 * Sets the cla_kpi local service.
	 *
	 * @param cla_kpiLocalService the cla_kpi local service
	 */
	public void setcla_kpiLocalService(
		com.astra.anblicks.pdca.service.cla_kpiLocalService cla_kpiLocalService) {
		this.cla_kpiLocalService = cla_kpiLocalService;
	}

	/**
	 * Returns the cla_kpi persistence.
	 *
	 * @return the cla_kpi persistence
	 */
	public cla_kpiPersistence getcla_kpiPersistence() {
		return cla_kpiPersistence;
	}

	/**
	 * Sets the cla_kpi persistence.
	 *
	 * @param cla_kpiPersistence the cla_kpi persistence
	 */
	public void setcla_kpiPersistence(cla_kpiPersistence cla_kpiPersistence) {
		this.cla_kpiPersistence = cla_kpiPersistence;
	}

	/**
	 * Returns the company local service.
	 *
	 * @return the company local service
	 */
	public com.astra.anblicks.pdca.service.companyLocalService getcompanyLocalService() {
		return companyLocalService;
	}

	/**
	 * Sets the company local service.
	 *
	 * @param companyLocalService the company local service
	 */
	public void setcompanyLocalService(
		com.astra.anblicks.pdca.service.companyLocalService companyLocalService) {
		this.companyLocalService = companyLocalService;
	}

	/**
	 * Returns the company persistence.
	 *
	 * @return the company persistence
	 */
	public companyPersistence getcompanyPersistence() {
		return companyPersistence;
	}

	/**
	 * Sets the company persistence.
	 *
	 * @param companyPersistence the company persistence
	 */
	public void setcompanyPersistence(companyPersistence companyPersistence) {
		this.companyPersistence = companyPersistence;
	}

	/**
	 * Returns the company_user local service.
	 *
	 * @return the company_user local service
	 */
	public com.astra.anblicks.pdca.service.company_userLocalService getcompany_userLocalService() {
		return company_userLocalService;
	}

	/**
	 * Sets the company_user local service.
	 *
	 * @param company_userLocalService the company_user local service
	 */
	public void setcompany_userLocalService(
		com.astra.anblicks.pdca.service.company_userLocalService company_userLocalService) {
		this.company_userLocalService = company_userLocalService;
	}

	/**
	 * Returns the company_user persistence.
	 *
	 * @return the company_user persistence
	 */
	public company_userPersistence getcompany_userPersistence() {
		return company_userPersistence;
	}

	/**
	 * Sets the company_user persistence.
	 *
	 * @param company_userPersistence the company_user persistence
	 */
	public void setcompany_userPersistence(
		company_userPersistence company_userPersistence) {
		this.company_userPersistence = company_userPersistence;
	}

	/**
	 * Returns the item description local service.
	 *
	 * @return the item description local service
	 */
	public com.astra.anblicks.pdca.service.itemDescriptionLocalService getitemDescriptionLocalService() {
		return itemDescriptionLocalService;
	}

	/**
	 * Sets the item description local service.
	 *
	 * @param itemDescriptionLocalService the item description local service
	 */
	public void setitemDescriptionLocalService(
		com.astra.anblicks.pdca.service.itemDescriptionLocalService itemDescriptionLocalService) {
		this.itemDescriptionLocalService = itemDescriptionLocalService;
	}

	/**
	 * Returns the item description persistence.
	 *
	 * @return the item description persistence
	 */
	public itemDescriptionPersistence getitemDescriptionPersistence() {
		return itemDescriptionPersistence;
	}

	/**
	 * Sets the item description persistence.
	 *
	 * @param itemDescriptionPersistence the item description persistence
	 */
	public void setitemDescriptionPersistence(
		itemDescriptionPersistence itemDescriptionPersistence) {
		this.itemDescriptionPersistence = itemDescriptionPersistence;
	}

	/**
	 * Returns the kpi local service.
	 *
	 * @return the kpi local service
	 */
	public com.astra.anblicks.pdca.service.kpiLocalService getkpiLocalService() {
		return kpiLocalService;
	}

	/**
	 * Sets the kpi local service.
	 *
	 * @param kpiLocalService the kpi local service
	 */
	public void setkpiLocalService(
		com.astra.anblicks.pdca.service.kpiLocalService kpiLocalService) {
		this.kpiLocalService = kpiLocalService;
	}

	/**
	 * Returns the kpi persistence.
	 *
	 * @return the kpi persistence
	 */
	public kpiPersistence getkpiPersistence() {
		return kpiPersistence;
	}

	/**
	 * Sets the kpi persistence.
	 *
	 * @param kpiPersistence the kpi persistence
	 */
	public void setkpiPersistence(kpiPersistence kpiPersistence) {
		this.kpiPersistence = kpiPersistence;
	}

	/**
	 * Returns the pdca_ admin settings local service.
	 *
	 * @return the pdca_ admin settings local service
	 */
	public com.astra.anblicks.pdca.service.pdca_AdminSettingsLocalService getpdca_AdminSettingsLocalService() {
		return pdca_AdminSettingsLocalService;
	}

	/**
	 * Sets the pdca_ admin settings local service.
	 *
	 * @param pdca_AdminSettingsLocalService the pdca_ admin settings local service
	 */
	public void setpdca_AdminSettingsLocalService(
		com.astra.anblicks.pdca.service.pdca_AdminSettingsLocalService pdca_AdminSettingsLocalService) {
		this.pdca_AdminSettingsLocalService = pdca_AdminSettingsLocalService;
	}

	/**
	 * Returns the pdca_ admin settings persistence.
	 *
	 * @return the pdca_ admin settings persistence
	 */
	public pdca_AdminSettingsPersistence getpdca_AdminSettingsPersistence() {
		return pdca_AdminSettingsPersistence;
	}

	/**
	 * Sets the pdca_ admin settings persistence.
	 *
	 * @param pdca_AdminSettingsPersistence the pdca_ admin settings persistence
	 */
	public void setpdca_AdminSettingsPersistence(
		pdca_AdminSettingsPersistence pdca_AdminSettingsPersistence) {
		this.pdca_AdminSettingsPersistence = pdca_AdminSettingsPersistence;
	}

	/**
	 * Returns the period local service.
	 *
	 * @return the period local service
	 */
	public com.astra.anblicks.pdca.service.periodLocalService getperiodLocalService() {
		return periodLocalService;
	}

	/**
	 * Sets the period local service.
	 *
	 * @param periodLocalService the period local service
	 */
	public void setperiodLocalService(
		com.astra.anblicks.pdca.service.periodLocalService periodLocalService) {
		this.periodLocalService = periodLocalService;
	}

	/**
	 * Returns the period persistence.
	 *
	 * @return the period persistence
	 */
	public periodPersistence getperiodPersistence() {
		return periodPersistence;
	}

	/**
	 * Sets the period persistence.
	 *
	 * @param periodPersistence the period persistence
	 */
	public void setperiodPersistence(periodPersistence periodPersistence) {
		this.periodPersistence = periodPersistence;
	}

	/**
	 * Returns the trading profit local service.
	 *
	 * @return the trading profit local service
	 */
	public com.astra.anblicks.pdca.service.tradingProfitLocalService gettradingProfitLocalService() {
		return tradingProfitLocalService;
	}

	/**
	 * Sets the trading profit local service.
	 *
	 * @param tradingProfitLocalService the trading profit local service
	 */
	public void settradingProfitLocalService(
		com.astra.anblicks.pdca.service.tradingProfitLocalService tradingProfitLocalService) {
		this.tradingProfitLocalService = tradingProfitLocalService;
	}

	/**
	 * Returns the trading profit persistence.
	 *
	 * @return the trading profit persistence
	 */
	public tradingProfitPersistence gettradingProfitPersistence() {
		return tradingProfitPersistence;
	}

	/**
	 * Sets the trading profit persistence.
	 *
	 * @param tradingProfitPersistence the trading profit persistence
	 */
	public void settradingProfitPersistence(
		tradingProfitPersistence tradingProfitPersistence) {
		this.tradingProfitPersistence = tradingProfitPersistence;
	}

	/**
	 * Returns the type local service.
	 *
	 * @return the type local service
	 */
	public com.astra.anblicks.pdca.service.typeLocalService gettypeLocalService() {
		return typeLocalService;
	}

	/**
	 * Sets the type local service.
	 *
	 * @param typeLocalService the type local service
	 */
	public void settypeLocalService(
		com.astra.anblicks.pdca.service.typeLocalService typeLocalService) {
		this.typeLocalService = typeLocalService;
	}

	/**
	 * Returns the type persistence.
	 *
	 * @return the type persistence
	 */
	public typePersistence gettypePersistence() {
		return typePersistence;
	}

	/**
	 * Sets the type persistence.
	 *
	 * @param typePersistence the type persistence
	 */
	public void settypePersistence(typePersistence typePersistence) {
		this.typePersistence = typePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.astra.anblicks.pdca.model.addkpi_ci",
			addkpi_ciLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.astra.anblicks.pdca.model.addkpi_ci");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return addkpi_ciLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return addkpi_ci.class;
	}

	protected String getModelClassName() {
		return addkpi_ci.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = addkpi_ciPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.astra.anblicks.pdca.service.achivementFormulaLocalService.class)
	protected com.astra.anblicks.pdca.service.achivementFormulaLocalService achivementFormulaLocalService;
	@BeanReference(type = achivementFormulaPersistence.class)
	protected achivementFormulaPersistence achivementFormulaPersistence;
	@BeanReference(type = addkpi_ciLocalService.class)
	protected addkpi_ciLocalService addkpi_ciLocalService;
	@BeanReference(type = addkpi_ciPersistence.class)
	protected addkpi_ciPersistence addkpi_ciPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.AstraPdca_CompanyDataLocalService.class)
	protected com.astra.anblicks.pdca.service.AstraPdca_CompanyDataLocalService astraPdca_CompanyDataLocalService;
	@BeanReference(type = AstraPdca_CompanyDataPersistence.class)
	protected AstraPdca_CompanyDataPersistence astraPdca_CompanyDataPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.AstraPdca_ModuleLocalService.class)
	protected com.astra.anblicks.pdca.service.AstraPdca_ModuleLocalService astraPdca_ModuleLocalService;
	@BeanReference(type = AstraPdca_ModulePersistence.class)
	protected AstraPdca_ModulePersistence astraPdca_ModulePersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.AstraPdca_YearLocalService.class)
	protected com.astra.anblicks.pdca.service.AstraPdca_YearLocalService astraPdca_YearLocalService;
	@BeanReference(type = AstraPdca_YearPersistence.class)
	protected AstraPdca_YearPersistence astraPdca_YearPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.ci_kpiLocalService.class)
	protected com.astra.anblicks.pdca.service.ci_kpiLocalService ci_kpiLocalService;
	@BeanReference(type = ci_kpiPersistence.class)
	protected ci_kpiPersistence ci_kpiPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.cla_kpiLocalService.class)
	protected com.astra.anblicks.pdca.service.cla_kpiLocalService cla_kpiLocalService;
	@BeanReference(type = cla_kpiPersistence.class)
	protected cla_kpiPersistence cla_kpiPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.companyLocalService.class)
	protected com.astra.anblicks.pdca.service.companyLocalService companyLocalService;
	@BeanReference(type = companyPersistence.class)
	protected companyPersistence companyPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.company_userLocalService.class)
	protected com.astra.anblicks.pdca.service.company_userLocalService company_userLocalService;
	@BeanReference(type = company_userPersistence.class)
	protected company_userPersistence company_userPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.itemDescriptionLocalService.class)
	protected com.astra.anblicks.pdca.service.itemDescriptionLocalService itemDescriptionLocalService;
	@BeanReference(type = itemDescriptionPersistence.class)
	protected itemDescriptionPersistence itemDescriptionPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.kpiLocalService.class)
	protected com.astra.anblicks.pdca.service.kpiLocalService kpiLocalService;
	@BeanReference(type = kpiPersistence.class)
	protected kpiPersistence kpiPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.pdca_AdminSettingsLocalService.class)
	protected com.astra.anblicks.pdca.service.pdca_AdminSettingsLocalService pdca_AdminSettingsLocalService;
	@BeanReference(type = pdca_AdminSettingsPersistence.class)
	protected pdca_AdminSettingsPersistence pdca_AdminSettingsPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.periodLocalService.class)
	protected com.astra.anblicks.pdca.service.periodLocalService periodLocalService;
	@BeanReference(type = periodPersistence.class)
	protected periodPersistence periodPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.tradingProfitLocalService.class)
	protected com.astra.anblicks.pdca.service.tradingProfitLocalService tradingProfitLocalService;
	@BeanReference(type = tradingProfitPersistence.class)
	protected tradingProfitPersistence tradingProfitPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.typeLocalService.class)
	protected com.astra.anblicks.pdca.service.typeLocalService typeLocalService;
	@BeanReference(type = typePersistence.class)
	protected typePersistence typePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}